version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - '80:3000'
    restart: always
    environment:
      - TZ=Asia/Hong_Kong
